Added "verbose debug mode" (RDOCKER_DEBUG=2). Streamlined env configuration.

diff --git a/bin/rdocker b/bin/rdocker
--- a/bin/rdocker
+++ b/bin/rdocker
@@ -2,9 +2,19 @@
 ####################################################################
 # rdocker - Remote Docker CLI
 ####################################################################
-# set -xe
+set -e
+
 RDOCKER_LOGPREFIX="[rdocker] "
 RDOCKER_VERSION="0.3.1"
+
+# Debug mode
+# 0: no debug
+# 1: debug
+# 2: verbose debug
+RDOCKER_DEBUG=${RDOCKER_DEBUG:-0}
+if [ $RDOCKER_DEBUG -eq 2 ]; then
+  set -x
+fi
 
 # get the directory of the script
 script_dir=$(dirname $(readlink -f $0))
@@ -15,111 +25,56 @@ source $script_dir/../lib/config.inc.sh
 # load the environment variables
 source $script_dir/../lib/env.inc.sh
 
-# check the context and setup the environment
-if [ -z "$RDOCKER_CONTEXT" ]; then
-  echoerr "RDOCKER_CONTEXT not set. Exiting"
-  exit 1
-fi
-# set the log prefix to the context
-RDOCKER_LOGPREFIX="[${RDOCKER_CONTEXT}] "
-# the docker socket on the remote host
-RDOCKER_REMOTE_SOCKET=${RDOCKER_REMOTE_SOCKET:-/var/run/docker.sock}
-# the tmp directory on the local host
-RDOCKER_LOCAL_TMPDIR=${RDOCKER_LOCAL_TMPDIR:-/tmp}
-# the docker socket on the local host
-RDOCKER_LOCAL_SOCKET=${RDOCKER_LOCAL_SOCKET:-}
-if [ -z "$RDOCKER_LOCAL_SOCKET" ]; then
-  RDOCKER_LOCAL_SOCKET=${RDOCKER_LOCAL_TMPDIR}/rdocker-docker.${RDOCKER_CONTEXT}.sock
-fi
-# the (R)DOCKER_HOST value used to connect to the remote host via the tunnel
-RDOCKER_HOST=unix://${RDOCKER_LOCAL_SOCKET}
-# the (Auto)SSH tunnel PID file
-RDOCKER_TUNNEL_PID_FILE=${RDOCKER_LOCAL_TMPDIR}/rdocker-ssh-tunnel.${RDOCKER_CONTEXT}.pid
-RDOCKER_SOCAT_PID_FILE=${RDOCKER_LOCAL_TMPDIR}/rdocker-socat.${RDOCKER_CONTEXT}.pid
-# local variable to skip auto-cleanup of the tunnel
-skip_cleanup=0
-
-RDOCKER_REMOTE_SSH_KEY=${RDOCKER_REMOTE_SSH_KEY:-}
-RDOCKER_REMOTE_SSH_KEY_PASS=${RDOCKER_REMOTE_SSH_KEY_PASS:-}
-RDOCKER_REMOTE_SSH_KEY_PASS_FILE=${RDOCKER_REMOTE_SSH_KEY_PASS_FILE:-}
-if [ -z "$RDOCKER_REMOTE_SSH_KEY" ]; then
-  if [ -f "${RDOCKER_HOME}/${RDOCKER_CONTEXT}.key" ]; then
-    RDOCKER_REMOTE_SSH_KEY="${RDOCKER_HOME}/${RDOCKER_CONTEXT}.key"
-
-    # check corresponding passphrase file
-    if [ -f "${RDOCKER_HOME}/${RDOCKER_CONTEXT}.key.pass" ]; then
-      RDOCKER_REMOTE_SSH_KEY_PASS_FILE="${RDOCKER_HOME}/${RDOCKER_CONTEXT}.key.pass"
-    fi
-  fi
-fi
-
-# read the passphrase from the file, if set
-if [ -n "$RDOCKER_REMOTE_SSH_KEY_PASS_FILE" ]; then
-  if [ -f "$RDOCKER_REMOTE_SSH_KEY_PASS_FILE" ]; then
-    RDOCKER_REMOTE_SSH_KEY_PASS=$(cat $RDOCKER_REMOTE_SSH_KEY_PASS_FILE)
-  else
-    echoerr "SSH key passphrase file not found: $RDOCKER_REMOTE_SSH_KEY_PASS_FILE"
-    exit 1
-  fi
-fi
-echolog "RDOCKER_REMOTE_SSH_KEY: $RDOCKER_REMOTE_SSH_KEY"
-echolog "RDOCKER_REMOTE_SSH_KEY_PASS_FILE: $RDOCKER_REMOTE_SSH_KEY_PASS_FILE"
-#echolog "RDOCKER_REMOTE_SSH_KEY_PASS: $RDOCKER_REMOTE_SSH_KEY_PASS"
-
 # ssh arguments
 SSH_ARGS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ExitOnForwardFailure=yes"
 AUTOSSH_ARGS=""
-# check if the SSH key is set
-if [ -n "$RDOCKER_REMOTE_SSH_KEY" ]; then
-  if [ -f "$RDOCKER_REMOTE_SSH_KEY" ]; then
 
-    #      # check if the key has a passphrase
-    #      if ssh-keygen -y -f $RDOCKER_REMOTE_SSH_KEY 2>&1 | grep -q "Enter passphrase for key"; then
-    #        # the key has a passphrase
-    #        if [ -z "$RDOCKER_REMOTE_SSH_KEY_PASS" ]; then
-    #          echoerr "SSH key has a passphrase. Please set RDOCKER_REMOTE_SSH_KEY_PASS"
-    #          exit 1
-    #        fi
-    #        #echo "SSH key has a passphrase"
-    #        #echo "RDOCKER_REMOTE_SSH_KEY_PASS: $RDOCKER_REMOTE_SSH_KEY_PASS"
-    #      fi
-    #    fi
+# local variable to skip auto-cleanup of the tunnel
+skip_cleanup=0
 
-    # unlock the SSH key if it has a passphrase
-    if [ -n "$RDOCKER_REMOTE_SSH_KEY_PASS" ]; then
-      echo "Unlocking SSH key with passphrase"
+function load_ssh_key() {
 
-      # spawn ssh-agent if not already running
-      if [ -z "$SSH_AUTH_SOCK" ]; then
-        eval $(ssh-agent -s)
-        if [ $? -ne 0 ]; then
-          echoerr "Failed to start ssh-agent. Exiting"
-          exit 1
+  # check if the SSH key is set
+  if [ -n "$RDOCKER_REMOTE_SSH_KEY" ]; then
+    if [ -f "$RDOCKER_REMOTE_SSH_KEY" ]; then
+
+      # unlock the SSH key if it has a passphrase
+      if [ -n "$RDOCKER_REMOTE_SSH_KEY_PASS" ]; then
+        echo "Unlocking SSH key with passphrase"
+
+        # spawn ssh-agent if not already running
+        if [ -z "$SSH_AUTH_SOCK" ]; then
+          eval $(ssh-agent -s)
+          if [ $? -ne 0 ]; then
+            echoerr "Failed to start ssh-agent. Exiting"
+            return 1
+          fi
         fi
-      fi
 
-      # workaround for passwords containing $ sign
-      # escape the $ sign
-      EXPECT_PASSWORD=$(echo "$RDOCKER_REMOTE_SSH_KEY_PASS" | sed 's/\$/\\$/g')
-      #echo "Expect password: $EXPECT_PASSWORD"
-      expect <<EOF
+        # workaround for passwords containing $ sign
+        # escape the $ sign
+        EXPECT_PASSWORD=$(echo "$RDOCKER_REMOTE_SSH_KEY_PASS" | sed 's/\$/\\$/g')
+        #echo "Expect password: $EXPECT_PASSWORD"
+        expect <<EOF
 spawn ssh-add "$RDOCKER_REMOTE_SSH_KEY"
 expect -re "Enter passphrase(.*):"
 send "$EXPECT_PASSWORD\r"
 expect eof
 EOF
-      if [ $? -ne 0 ]; then
-        echoerr "Failed to unlock SSH key. Exiting"
-        exit 1
+        if [ $? -ne 0 ]; then
+          echoerr "Failed to unlock SSH key. Exiting"
+          return 1
+        fi
       fi
+    else
+      echoerr "SSH key file not found: $RDOCKER_REMOTE_SSH_KEY"
+      return 1
     fi
-
-    SSH_ARGS="$SSH_ARGS -o IdentitiesOnly=yes -i $RDOCKER_REMOTE_SSH_KEY"
-  else
-    echoerr "SSH key file not found: $RDOCKER_REMOTE_SSH_KEY"
-    exit 1
   fi
-fi
+
+ return 0
+}
+
 #echolog "SSH_ARGS: $SSH_ARGS"
 #echolog "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
 
@@ -132,12 +87,12 @@ SOCAT_PID=
 function setup_autossh_tunnel() {
   if [ -z "$RDOCKER_REMOTE_HOST" ]; then
     echoerr "RDOCKER_REMOTE_HOST not defined. Exiting"
-    exit 1
+    return 1
   fi
 
   if [ -z "$RDOCKER_REMOTE_USER" ]; then
     echoerr "RDOCKER_REMOTE_USER not defined. Exiting"
-    exit 1
+    return 1
   fi
 
   # check if a tunnel is already running
@@ -147,8 +102,18 @@ function setup_autossh_tunnel() {
       echoerr "SSH tunnel already up. PID: $SSH_PID"
       skip_cleanup=1
       #return 0
-      exit 0
+      return 0
     fi
+  fi
+
+  # load the SSH key, if defined
+  # unlock the SSH key if it has a passphrase
+  if ! load_ssh_key; then
+    echoerr "Failed to load SSH key. Exiting"
+    return 1
+  fi
+  if [ -n "$RDOCKER_REMOTE_SSH_KEY" ]; then
+    SSH_ARGS="$SSH_ARGS -o IdentitiesOnly=yes -i $RDOCKER_REMOTE_SSH_KEY"
   fi
 
   echolog "Setting up autossh tunnel to ${RDOCKER_REMOTE_HOST}"
@@ -164,7 +129,7 @@ function setup_autossh_tunnel() {
   # check if the autossh process is running
   if ! kill -0 "$SSH_PID" 2>/dev/null; then
     echoerr "SSH tunnel failed to start. Exiting"
-    exit 1
+    return 1
   fi
   echo $SSH_PID > "$RDOCKER_TUNNEL_PID_FILE"
   echolog "Tunnel started. PID: $(cat $RDOCKER_TUNNEL_PID_FILE)"
@@ -288,7 +253,13 @@ function print_context() {
   echo "* RDOCKER_CONTEXT: $RDOCKER_CONTEXT"
   echo "* RDOCKER_REMOTE_HOST: $RDOCKER_REMOTE_HOST"
   echo "* RDOCKER_REMOTE_USER: $RDOCKER_REMOTE_USER"
+  echo "* RDOCKER_REMOTE_SSH_KEY: $RDOCKER_REMOTE_SSH_KEY"
   echo "* RDOCKER_REMOTE_SOCKET: $RDOCKER_REMOTE_SOCKET"
+  echo "* RDOCKER_LOCAL_TMPDIR: $RDOCKER_LOCAL_TMPDIR"
+  echo "* RDOCKER_TUNNEL_PID_FILE: $RDOCKER_TUNNEL_PID_FILE"
+  echo "* RDOCKER_SOCAT_PID_FILE: $RDOCKER_SOCAT_PID_FILE"
+  echo "* RDOCKER_TCP_PORT: $RDOCKER_TCP_PORT"
+  echo "* RDOCKER_TCP_ENABLE: $RDOCKER_TCP_ENABLE"
   echo "* RDOCKER_LOCAL_SOCKET: $RDOCKER_LOCAL_SOCKET"
   echo "* RDOCKER_HOST: $RDOCKER_HOST"
   echo "-----------------------"
@@ -395,7 +366,10 @@ EOF
   "tunnel-up")
     print_context
     #setup_tunnel
-    setup_autossh_tunnel
+    if ! setup_autossh_tunnel ; then
+      echoerr "Failed to setup SSH tunnel. Exiting"
+      exit 1
+    fi
     setup_docker_context "${RDOCKER_CONTEXT}" "unix://${RDOCKER_LOCAL_SOCKET}"
 
     echo "🔐 SSH tunnel established to ${RDOCKER_REMOTE_HOST}"
@@ -421,7 +395,7 @@ EOF
     sleep 1
     echo "Press Ctrl+C to close tunnel and exit."
     while true; do
-      sleep 3
+      # check if the SSH tunnel is still running ...
       if [ -f $RDOCKER_TUNNEL_PID_FILE ]; then
         SSH_PID=$(cat $RDOCKER_TUNNEL_PID_FILE)
         if ! kill -0 "$SSH_PID" 2>/dev/null; then
@@ -434,9 +408,10 @@ EOF
         exit 92
       fi
 
-      #clear
-      #$DOCKER_BIN ps
-      #echo "Press Ctrl+C to exit."
+      # ... every 30 seconds
+      # @todo make check interval configurable
+      sleep 30
+
     done
     exit 0
   ;;
@@ -454,7 +429,10 @@ EOF
     # The trap will cleanup the tunnel on exit.
 
     #setup_tunnel
-    setup_autossh_tunnel
+    if ! setup_autossh_tunnel ; then
+      echoerr "Failed to setup SSH tunnel. Exiting"
+      exit 1
+    fi
 
     export DOCKER_HOST=${RDOCKER_HOST}
     echolog "DOCKER_HOST=$DOCKER_HOST"
